USE BVA_UNIVER
GO
--1--

CREATE TABLE TABLE1
(T1 INT,
T2 INT,
T3 INT);

DECLARE @X INT;
SET @X = ((SELECT COUNT(*) FROM PROFESSION));
PRINT (@X);
INSERT INTO TABLE1(T1, T2, T3)
VALUES (@X, (SELECT COUNT(*) FROM SUBJECT), (SELECT COUNT(*) FROM FACULTY))

SELECT *FROM TABLE1;
--2--
UPDATE PROGRESS SET NOTE = 6 WHERE PROGRESS.IDSTUDENT IN(
SELECT STUDENT.IDSTUDENT
FROM STUDENT JOIN GROUPS
ON STUDENT.IDGROUP = GROUPS.IDGROUP
JOIN PROFESSION
ON PROFESSION.PROFESSION = GROUPS.PROFESSION AND PROFESSION.QUALIFICATION LIKE '%“≈’ÕŒÀŒ√%'
JOIN PROGRESS
ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
JOIN SUBJECT
ON PROGRESS.SUBJECT = SUBJECT.SUBJECT AND SUBJECT.SUBJECT_NAME LIKE '%’»Ã»ﬂ%');
SELECT *FROM PROGRESS;

--3--
SELECT STUDENT.IDSTUDENT,STUDENT.NAME AS 'STUDENT NAME'
FROM STUDENT
WHERE STUDENT.IDSTUDENT <= ALL(SELECT PROGRESS.IDSTUDENT FROM PROGRESS)

--4--
SELECT STUDENT.IDGROUP, AVG(DATEDIFF(YEAR, STUDENT.BDAY, GETDATE())) [—–.¬Œ«–¿—“]
FROM STUDENT 
GROUP BY STUDENT.IDGROUP;

SELECT GROUPS.FACULTY, AVG(DATEDIFF(YEAR, STUDENT.BDAY, GETDATE())) [—–.¬Œ«–¿—“]
FROM STUDENT, GROUPS 
WHERE STUDENT.IDGROUP = GROUPS.IDGROUP 
GROUP BY GROUPS.FACULTY;

--5--
SELECT ST1.IDGROUP, (SELECT AVG(DATEDIFF(YEAR, ST2.BDAY, GETDATE()))
FROM STUDENT ST2 WHERE ST1.IDGROUP = ST2.IDGROUP)[—–.¬Œ«–¿—“]
FROM STUDENT ST1
GROUP BY ST1.IDGROUP
INTERSECT
--EXCEPT--
SELECT ST.IDGROUP, AVG(DATEDIFF(YEAR, ST.BDAY, GETDATE())) [—–.¬Œ«–¿—“]
FROM STUDENT ST 
GROUP BY ST.IDGROUP;


--6--
GO
CREATE VIEW DEL
AS SELECT *
FROM STUDENT;
GO

SELECT *FROM TABLE1;
SELECT *FROM DEL;
DROP TABLE TABLE1;
DROP VIEW DEL;


